Add Python 3.9 support
Qiskit/qiskit-aer pull request #1071
Opened 2020-12-07 20:03 UTC by mtreinish

### Summary

This commit adds official python 3.9 support to qiskit-aer. This
includes CI, release notes, and package metadata.

### Details and comments

Fixes #1067

2020-12-07 20:28 UTC, mtreinish commented
It looks like python 3.9 builds work fine (and passes verify wheels), but there are some CI issues for the tests jobs around cvxpy and related on python 3.9 that are blocking those

2020-12-09 12:58 UTC, mtreinish commented
One thing to note here is that since #1074 we're not trying to test the noise transformations on Python 3.9 anymore as we're no longer installing cvxpy outside of python 3.7 and 3.8. There were issues installing cvxpy because of scs with 3.9.

2020-12-10 07:52 UTC, vvilpas requested changes
Looks good! Just a small typo.

2020-12-10 12:51 UTC, mtreinish commented on azure-pipelines.yml
> +            Python38:
I fixed this issue yesterday to unblock the azure runs: https://github.com/Qiskit/qiskit-aer/pull/1071/commits/bb99ae1cb6283ae478c34799fe7a65aaaf7b1f61 I think you might have been looking at a stale diff.

2020-12-10 13:32 UTC, vvilpas commented on azure-pipelines.yml
> +            Python38:
Right! Sorry about that.

2020-12-10 15:14 UTC, vvilpas approved these changes

2020-12-10 15:14 UTC, merged