Fixed normalization in MPS truncation
Qiskit/qiskit-aer pull request #1094
Opened 2021-01-06 13:50 UTC by yaelbh

A bug fix in MPS, relevant especially to approximation

2021-01-06 19:09 UTC, merav-aharoni commented
Wow - nice catch, @yaelbh

2021-01-12 22:36 UTC, chriseclectic approved these changes

2021-01-12 22:36 UTC, chriseclectic requested changes
If this is fixing something that is in a stable release can you add a release note detailing the big fix.

Something like "fixes a bug when applying truncation in the matrix product state method of the QasmSimulator".

2021-01-17 12:07 UTC, yaelbh commented
@chriseclectic done

2021-01-18 10:03 UTC, vvilpas approved these changes

2021-01-18 10:04 UTC, merged