[WIP] Configurable backends
Qiskit/qiskit-aer pull request #486
Opened 2019-12-09 21:21 UTC by chriseclectic

### Summary

Makes simulator backends have configurable persistent values for `backend_options`.

For the `QasmSimulator` backend_options for noise model and simulation method have special kwargs `noise_model` and simulation `method` for direct configuration without using a backend_options dict.

### Details and comments

Configurable backends can be specified during creation of the simulation object. Eg

```python
# Make a Clifford stabilizer simulator backend
backend = QasmSimulator(method='stabilizer', noise_model=noise_model)

# Run noisy stabilizer simulations
job = execute(circuits, backend)  
```

This will return the appropriate configuration for allowed gates for the different qasm simulator methods.

Parameters can still be overriden at runtime using the original kwargs eg:

```python
# Override backend to run density matrix simulation with new noise model
job = execute(circs, backend, method='density_matrix, noise_model=new_noise)
```

2020-03-03 16:29 UTC, nonhermitian commented
This is cool.

It would be extra cool if Aer could autogen the noisy sims from those found doing `IBMQ.load_account()` or from Terra mock backends if no IBMQ such that one can simply do:

```python
sim = Aer.get_backend('vigo_simulator')
job = execute([qc], sim)
...
```

2020-09-14 08:09 UTC, vvilpas requested changes
Looks good. I have some very minor comments/sugggestions (most of them remainders to add 'cy' in list of basis)

2020-10-05 17:07 UTC, chriseclectic commented on qiskit/providers/aer/backends/pulse_simulator.py
> +                     'system model may result in inconsistencies.')
Im not sure, @DanPuzzuoli what do you think?

2020-10-05 17:29 UTC, DanPuzzuoli commented on qiskit/providers/aer/backends/pulse_simulator.py
> +                     'system model may result in inconsistencies.')
I figured a warning gives a bit more flexibility, enabling the user to independently specify a system model without having to modify other backend attributes. At the same time, I don't have a very clear/obvious use-case for this, and in any case if we change it to an exception, the user could still specify an independent system model by first deleting the Hamiltonian. I think personally I'm leaning towards keeping it as is and leaving it up to the user to choose what to do, though changing it to an exception does keep the object state "cleaner".

2020-10-10 15:45 UTC, vvilpas submitted a review, later dismissed

2020-10-12 19:00 UTC, mtreinish submitted a review, later dismissed
At a high level this looks good to me. It aligns with the model we're moving towards in Qiskit/qiskit-terra#5086 and puts us in a good place to switch over to that in the next aer release. The only piece missing is the default options (which being none is fine for a default) to define which options are available for a backend. Right now there isn't an easily discoverable way since everything is done via kwargs besides reading the docs. But, that's fine to do in a follow up when we migrate this Aer to be a v2 provider.

I just had a question inline and a doc suggestion, but easy enough to fix in a follow up.

2020-10-13 15:25 UTC, chriseclectic commented on releasenotes/notes/configurable-backends-a55cd6a39a0a1561.yaml
> +    an IBMQ backend object using the
In principle it could would work for any backend with `Configuration` and `BackendProperties` that have the required information.

2020-10-13 15:27 UTC, chriseclectic commented on qiskit/providers/aer/aerjob.py
> +    def __init__(self, backend, job_id, fn, qobj, *args, **kwargs):
I'll have to double check this. I had to do some fiddling to make it backwards compatible with Aqua quantum instance code

2020-10-13 15:45 UTC, chriseclectic commented on qiskit/providers/aer/aerjob.py
> +    def __init__(self, backend, job_id, fn, qobj, *args, **kwargs):
So I think kwargs are unneeded here now, i'll remove them. The args deprecation is due to aqua construction Job objects directly.

2020-10-13 19:45 UTC, merged