[WIP] Renew new benchmark
Qiskit/qiskit-aer pull request #940
Opened 2020-09-18 09:59 UTC by hhorii

### Summary

Renew asv benchmark for continuous performance evaluation

### Details and comments

This PR aims to renew asv benchmark for qiskit-aer.

In addition, this PR allows users to check performance with shell. 

```
cd test/
PYTHONPATH=./ python -u benchmark2/particular_quantum_circuits.py
```

- [ ] Evaluate most of circuits in Qiskit Circuit Library
- [ ] Evaluate noise simulation
- [ ] Evaluate sampling and expectation value calculation
- [ ] Support Linux environment
- [ ] Support mac environment
- [ ] Evaluate chemistry application
- [ ] Add command line arguments to specify benchmark configuration

2020-10-26 21:33 UTC, hhorii commented
Sampled results are here: https://hhorii.github.io/qiskit-aer/html/

2020-10-30 10:23 UTC, vvilpas requested changes
Looks good.
A couple of things:
1) Maybe we should split `asv.macos.conf.json` file in regular and cuda one as in linux.
2) Is dir benchmark.bak needed? If not, we can delete it.
3) There are some commented sections in the code (see comments) that I guess we can remove.

2020-10-30 10:23 UTC, vvilpas commented on test/benchmark/basic.py
> +    #    self._run(self.RUNTIME_UNITARY_MATRIX_GPU, app, qubit)
Remove?

2020-10-30 10:23 UTC, vvilpas commented on test/benchmark/noise.py
> +    #    self._run(self.RUNTIME_UNITARY_MATRIX_GPU, app, qubit)
Remove?

2020-10-30 10:23 UTC, vvilpas commented on test/benchmark/output.py
> +    #    self._run(self.RUNTIME_UNITARY_MATRIX_GPU, app, qubit)
Remove?

2020-10-30 10:23 UTC, vvilpas commented on test/benchmark/simulator_benchmark.py
> +        #    self.backend_qubits[self.RUNTIME_EXTENDED_STABILIZER_CPU] = self.qubits
Remove?

2020-10-30 10:23 UTC, vvilpas commented on test/benchmark/vqe_benchmark.py
> +            #'Li2O': 'Li .0 .0 -3.0; O .0 .0 .0; Li .0 .0 3.0',    # qubits: ...
Remove?

2020-11-02 02:11 UTC, hhorii commented on test/asv.macos.conf.json
> +        "python setup.py bdist_wheel --dist-dir={build_cache_dir} -- -DCMAKE_CXX_COMPILER=g++ -DAER_THRUST_BACKEND=CUDA -- -j"
Right. CUDA is not supported. Also, currently, MacOS is not tested. I would like to take it.

2020-11-03 08:02 UTC, vvilpas requested changes
Can we restore `asv.macos.conf.json` in case someone with a mac wants to run the benchmark locally (just remove the `-DAER_THRUST_BACKEND=CUDA`)? Or can we use the `linux` one on macos?
Other than that I think everything is ok.

2020-11-03 14:39 UTC, hhorii commented
@vvilpas I confirmed that `asv.linux.conf.json` works on Mac. But I guess that it doesn't work on Windows.

2020-11-03 14:43 UTC, vvilpas commented
> @vvilpas I confirmed that `asv.linux.conf.json` works on Mac. But I guess that it doesn't work on Windows.

I think we can add it later in case we need it.

2020-11-03 14:43 UTC, vvilpas approved these changes

2020-11-05 00:08 UTC, merged